name: CI
on:
  push:
    branches: [ master, deploy ]
  pull_request:
    branches: [ master, deploy ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn      
        
      - name: Build
        run: yarn build
        
      - name: Test
        run: yarn test --watchAll=false
